### ISSUE TITLE
cabt reach BePasty

### ISSUE THREAD

**Issue by phantomse** [asmaps/bepasty-docker#2]
docker run -d --restart=always --name BePasty \
-p 192.168.1.5:5066:5000  \
-v /AppConfig/BePasty:/srv/bepasty:rw asmaps/bepasty
cant access at 192.168.1.5:5066
tried multiple options with -p x:x
every time i get in log a new random port it seams
ex:
uwsgi socket 0 bound to TCP address 127.0.0.1:37591 (port auto-assigned) fd 3
or ex:
[uwsgi-http key: 192.168.1.5:5000 client_addr: 192.168.1.132 client_port: 61940] hr_instance_read(): Connection reset by peer [plugins/http/http.c line 637]

**Comment by asmaps** [comment]
what does `docker ps` say?
